CREATE DATABASE DIN_HMMC;
USE DIN_HMMC;

CREATE TABLE USER (
	USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    DESCRIPTION TEXT,
    GENDER ENUM ("MALE", "FEMALE", "NON_BINARY", "OTHER")
);